/**
 * Deterministic-ish test data generators for Playwright specs
 * (INT-024 · Sprint-17).
 *
 * Each factory appends a timestamp suffix so parallel workers cannot
 * collide on unique fields (PO numbers, importer IDs, etc.).
 */

const suffix = () =>
  `${Date.now().toString(36)}${Math.floor(Math.random() * 1e4)
    .toString(36)
    .padStart(3, '0')}`;

export function makeOrderPayload(overrides: Partial<OrderPayload> = {}): OrderPayload {
  return {
    importer_id: 'IMP-ACME',
    po_reference: `PO-E2E-${suffix().toUpperCase()}`,
    ...overrides,
  };
}

export interface OrderPayload {
  importer_id: string;
  po_reference: string;
  notes?: string;
}

export function makeImporterPayload(overrides: Partial<ImporterPayload> = {}): ImporterPayload {
  return {
    name: `E2E Importer ${suffix()}`,
    country: 'US',
    contact_email: `qa+${suffix()}@example.com`,
    ...overrides,
  };
}

export interface ImporterPayload {
  name: string;
  country: string;
  contact_email: string;
}

export function makeRulePayload(overrides: Partial<RulePayload> = {}): RulePayload {
  return {
    name: `E2E rule ${suffix()}`,
    description: 'Auto-generated by Playwright suite',
    dsl: 'item.case_qty > 0',
    severity: 'warn',
    ...overrides,
  };
}

export interface RulePayload {
  name: string;
  description: string;
  dsl: string;
  severity: 'info' | 'warn' | 'error';
}

export function makeWarningLabelPayload(overrides: Partial<WarningLabelPayload> = {}): WarningLabelPayload {
  return {
    sku: `SKU-E2E-${suffix().toUpperCase()}`,
    product_name: 'Scented candle (test)',
    country: 'US',
    ...overrides,
  };
}

export interface WarningLabelPayload {
  sku: string;
  product_name: string;
  country: string;
}
